name: modern_living
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_rating_bar: ^3.2.0+1
  badges: ^1.1.6
  provider: ^4.3.2+4
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0
  firebase_analytics: ^7.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - asset/images/
  fonts:
    - family: PoppinsMedium
      fonts:
        - asset: asset/fonts/PoppinsMedium.ttf
        - asset: asset/fonts/PoppinsSemiBold.ttf


